[package]
name = "rust-scratch-public"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["btree-ob-eval"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
